openapi: 3.0.3
info:
  title: ConnectSocial API
  version: 1.0.0
  description: API documentation for ConnectSocial project

paths:
  /api/auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistrationRequest'
      responses:
        '200':
          description: User registration successful
        '400':
          description: Bad request

  /api/auth/login:
    post:
      summary: Log in a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoginRequest'
      responses:
        '200':
          description: User login successful
        '401':
          description: Unauthorized
        '400':
          description: Bad request

  /api/auth/logout:
    post:
      summary: Log out a user
      responses:
        '200':
          description: User logout successful

  /api/auth/reset-password:
    post:
      summary: Reset user's password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordResetRequest'
      responses:
        '200':
          description: Password reset successful
        '400':
          description: Bad request

  /api/auth/recover-account:
    post:
      summary: Recover a locked or compromised user account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountRecoveryRequest'
      responses:
        '200':
          description: Account recovery successful
        '400':
          description: Bad request

  /api/social-media/accounts:
    get:
      summary: Retrieve connected social media accounts of a user
      responses:
        '200':
          description: Social media accounts retrieved successfully

  /api/social-media/accounts/connect:
    post:
      summary: Connect a social media account to ConnectSocial
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SocialMediaAccountConnectRequest'
      responses:
        '200':
          description: Social media account connected successfully
        '400':
          description: Bad request

  /api/social-media/accounts/disconnect:
    post:
      summary: Disconnect a social media account from ConnectSocial
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SocialMediaAccountDisconnectRequest'
      responses:
        '200':
          description: Social media account disconnected successfully
        '400':
          description: Bad request

# Add other paths for remaining APIs following a similar structure...

components:
  schemas:
    UserRegistrationRequest:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string

    UserLoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string

    PasswordResetRequest:
      type: object
      properties:
        email:
          type: string

    AccountRecoveryRequest:
      type: object
      properties:
        email:
          type: string

    SocialMediaAccountConnectRequest:
      type: object
      properties:
        platform:
          type: string
        accessToken:
          type: string
        refreshToken:
          type: string

    SocialMediaAccountDisconnectRequest:
      type: object
      properties:
        platform:
          type: string